name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Blazor WebAssembly project
        run: dotnet publish UMMB-Trombones/UMMB-Trombones.csproj -c Release -o publish

      - name: Prepare docs folder
        run: |
          mkdir docs
          mv publish/wwwroot/* docs/
          touch docs/.nojekyll

      - name: Commit and push to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy Blazor WASM to docs"
          git push
