name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Blazor WebAssembly project
        run: dotnet publish UMMB-Trombones/UMMB-Trombones.csproj -c Release -o docs

      - name: Move files out of wwwroot (so they're at root of docs/)
        run: |
          mkdir temp
          mv docs/wwwroot/* temp/
          rm -rf docs/*
          mv temp/* docs/

      - name: Disable Jekyll
        run: touch docs/.nojekyll

      - name: Deploy Blazor WebAssembly to GitHub Pages
        uses: na1307/blazor-github-pages@v3.0
        with:
          project-path: UMMB-Trombones/UMMB-Trombones.csproj
          publish-path: docs
